<?php

/**
 * Hand-curated package list — we share the backend's installed vendor but
 * don't auto-discover its providers (Filament et al. would crash on the
 * smaller shop install). Only register what Vanilo + Sanctum need.
 *
 * This file is regenerated by `php artisan package:discover`; the startup
 * command removes it on each boot so this list is the source of truth.
 */
return [
    'konekt/concord' => [
        'providers' => [
            'Konekt\\Concord\\ConcordServiceProvider',
        ],
        'aliases' => [
            'Helper' => 'Konekt\\Concord\\Facades\\Helper',
            'Concord' => 'Konekt\\Concord\\Facades\\Concord',
        ],
    ],
    'konekt/enum-eloquent' => [
        'providers' => [
            'Konekt\\Enum\\Eloquent\\EnumServiceProvider',
        ],
    ],
    'konekt/laravel-migration-compatibility' => [
        'providers' => [
            'Konekt\\LaravelMigrationCompatibility\\LaravelMigrationCompatibilityProvider',
        ],
    ],
    'laravel/sanctum' => [
        'providers' => [
            'Laravel\\Sanctum\\SanctumServiceProvider',
        ],
    ],
];
